import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import SectionContainer from "@/components/SectionContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CRUD App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <SectionContainer>{children}</SectionContainer>
      </body>
    </html>
  );
}
